version: 1
database: .codeatlas/github-test.db
cache_dir: .codeatlas/github-test-cache

index:
  include:
    - "**/*.c"
    - "**/*.h"
    - "**/*.grl"
    - "**/*.grl2"
  exclude:
    - "**/.git/**"
  max_file_bytes: 5000000
  artifact_kinds:
    grr:
      - ".grl"
      - ".grl2"

repositories:
  github-errm-selct-emivar-test:
    module: "ERRM"
    url: "https://github.com/AndreiRomanC/codeatlas-errm-selct-emivar-test.git"
    revisions:
      - name: "main"
        ref: "main"
        kind: "branch"

specification:
  provider: "folder_txt"
  repository: "github-errm-selct-emivar-test"
  revision: "main"
  directory_pattern: "agf/{module}/d"
  recursive: false
  max_file_bytes: 250000
